color: null
fieldLayouts:
  72401097-926c-4d25-9894-f803c3f5c9c7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b1337a8f-1a93-4112-80b8-fde4cf3c3dbc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7bc23fae-4faf-429b-abc8-070756505860 # Content Block
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50e46e96-2f99-49b4-97fa-02954e3940f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 76008731-bfc8-4458-a564-3dd449913666
        userCondition: null
handle: getAmped
hasTitleField: true
icon: ''
name: 'Get Amped'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
