columnSuffix: null
handle: contentBlock
instructions: null
name: 'Content Block'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 08c3bb98-4bb4-46c8-9770-01e7357473a8 # Code
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
